// Register
export const REGISTER_CLIENT_START = 'REGISTER_CLIENT_START';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAIL = 'REGISTER_CLIENT_FAIL';

export const REGISTER_AGENT_START = 'REGISTER_AGENT_START';
export const REGISTER_AGENT_SUCCESS = 'REGISTER_AGENT_SUCCESS';
export const REGISTER_AGENT_FAIL = 'REGISTER_AGENT_FAIL';

// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Login with Facebook
export const CLIENT_FACEBOOK_LOGIN_START = 'CLIENT_FACEBOOK_LOGIN_START';
export const CLIENT_FACEBOOK_LOGIN_SUCCESS = 'CLIENT_FACEBOOK_LOGIN_SUCCESS';
export const CLIENT_FACEBOOK_LOGIN_FAIL = 'CLIENT_FACEBOOK_LOGIN_FAIL';

// Properties
export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAIL = 'FETCH_PROPERTIES_FAIL';

// SHOW Property
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';

// Create Property
export const CREATE_PROPERTY_START = 'CREATE_PROPERTY_START';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAIL = 'CREATE_PROPERTY_FAIL';

// Update Property
export const UPDATE_PROPERTY_START = 'UPDATE_PROPERTY_START';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_FAIL = 'UPDATE_PROPERTY_FAIL';

// Delete Property
export const DELETE_PROPERTY_START = 'DELETE_PROPERTY_START';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAIL = 'DELETE_PROPERTY_FAIL';

// Services
export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICE_START = 'FETCH_SERVICE_START';
export const FETCH_SERVICE_FAIL = 'FETCH_SERVICE_FAIL';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';

// Cities
export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';

// Neightborhoods
export const FETCH_NEIGHTBORHOODS_START = 'FETCH_NEIGHTBORHOODS_START';
export const FETCH_NEIGHTBORHOODS_FAIL = 'FETCH_NEIGHTBORHOODS_FAIL';
export const FETCH_NEIGHTBORHOODS_SUCCESS = 'FETCH_NEIGHTBORHOODS_SUCCESS';

// Jobs
export const CREATE_JOB_START = 'CREATE_JOB_START';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';

export const FETCH_NEXTJOBS_START = 'FETCH_NEXTJOBS_START';
export const FETCH_NEXTJOBS_SUCCESS = 'FETCH_NEXTJOBS_SUCCESS';
export const FETCH_NEXTJOBS_FAIL = 'FETCH_NEXTJOBS_FAIL';

export const FETCH_HISTORYJOBS_START = 'FETCH_HISTORYJOBS_START';
export const FETCH_HISTORYJOBS_SUCCESS = 'FETCH_HISTORYJOBS_SUCCESS';
export const FETCH_HISTORYJOBS_FAIL = 'FETCH_HISTORYJOBS_FAIL';

export const FETCH_JOB_START = 'FETCH_JOB_START';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

export const ACCEPTED_JOB_START = 'ACCEPTED_JOB_START';
export const ACCEPTED_JOB_SUCCESS = 'ACCEPTED_JOB_SUCCESS';
export const ACCEPTED_JOB_FAIL = 'ACCEPTED_JOB_FAIL';

export const CANCELLED_JOB_START = 'CANCELLED_JOB_START';
export const CANCELLED_JOB_SUCCESS = 'CANCELLED_JOB_SUCCESS';
export const CANCELLED_JOB_FAIL = 'CANCELLED_JOB_FAIL';

export const FETCH_AGENT_JOBS_START = 'FETCH_AGENT_JOBS_START';
export const FETCH_AGENT_JOBS_SUCCESS = 'FETCH_AGENT_JOBS_SUCCESS';
export const FETCH_AGENT_JOBS_FAIL = 'FETCH_AGENT_JOBS_FAIL';

// Current user
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

export const UPDATED_CURRENT_USER_START = 'UPDATED_CURRENT_USER_START';
export const UPDATED_CURRENT_USER_SUCCESS = 'UPDATED_CURRENT_USER_SUCCESS';
export const UPDATED_CURRENT_USER_FAIL = 'UPDATED_CURRENT_USER_FAIL';

export const UPDATED_CURRENT_USER_AVATAR_START = 'UPDATED_CURRENT_USER_AVATAR_START';
export const UPDATED_CURRENT_USER_AVATAR_SUCCESS = 'UPDATED_CURRENT_USER_AVATAR_SUCCESS';
export const UPDATED_CURRENT_USER_AVATAR_FAIL = 'UPDATED_CURRENT_USER_AVATAR_FAIL';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const FETCH_CURRENT_AGENT_START = 'FETCH_CURRENT_AGENT_START';
export const FETCH_CURRENT_AGENT_FAIL = 'FETCH_CURRENT_AGENT_FAIL';
export const FETCH_CURRENT_AGENT_SUCCESS = 'FETCH_CURRENT_AGENT_SUCCESS';

export const UPDATED_CURRENT_AGENT_START = 'UPDATED_CURRENT_AGENT_START';
export const UPDATED_CURRENT_AGENT_SUCCESS = 'UPDATED_CURRENT_AGENT_SUCCESS';
export const UPDATED_CURRENT_AGENT_FAIL = 'UPDATED_CURRENT_AGENT_FAIL';

export const UPDATED_CURRENT_AGENT_AVATAR_START = 'UPDATED_CURRENT_AGENT_AVATAR_START';
export const UPDATED_CURRENT_AGENT_AVATAR_SUCCESS = 'UPDATED_CURRENT_AGENT_AVATAR_SUCCESS';
export const UPDATED_CURRENT_AGENT_AVATAR_FAIL = 'UPDATED_CURRENT_AGENT_AVATAR_FAIL';

export const CHANGE_PASSWORD_AGENT_START = 'CHANGE_PASSWORD_AGENT_START';
export const CHANGE_PASSWORD_AGENT_SUCCESS = 'CHANGE_PASSWORD_AGENT_SUCCESS';
export const CHANGE_PASSWORD_AGENT_FAIL = 'CHANGE_PASSWORD_AGENT_FAIL';
