// Register for clients
export const REGISTER_CLIENT_START = 'REGISTER_CLIENT_START';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAIL = 'REGISTER_CLIENT_FAIL';

// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Login with Facebook
export const CLIENT_FACEBOOK_LOGIN_START = 'CLIENT_FACEBOOK_LOGIN_START';
export const CLIENT_FACEBOOK_LOGIN_SUCCESS = 'CLIENT_FACEBOOK_LOGIN_SUCCESS';
export const CLIENT_FACEBOOK_LOGIN_FAIL = 'CLIENT_FACEBOOK_LOGIN_FAIL';

// Properties
export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAIL = 'FETCH_PROPERTIES_FAIL';

// SHOW Property
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';

// Create Property
export const CREATE_PROPERTY_START = 'CREATE_PROPERTY_START';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAIL = 'CREATE_PROPERTY_FAIL';

// Update Property
export const UPDATE_PROPERTY_START = 'UPDATE_PROPERTY_START';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_FAIL = 'UPDATE_PROPERTY_FAIL';

// Delete Property
export const DELETE_PROPERTY_START = 'DELETE_PROPERTY_START';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAIL = 'DELETE_PROPERTY_FAIL';

// Services
export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICE_START = 'FETCH_SERVICE_START';
export const FETCH_SERVICE_FAIL = 'FETCH_SERVICE_FAIL';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';

// Cities
export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';

// Neightborhoods
export const FETCH_NEIGHTBORHOODS_START = 'FETCH_NEIGHTBORHOODS_START';
export const FETCH_NEIGHTBORHOODS_FAIL = 'FETCH_NEIGHTBORHOODS_FAIL';
export const FETCH_NEIGHTBORHOODS_SUCCESS = 'FETCH_NEIGHTBORHOODS_SUCCESS';

// Jobs
export const CREATE_JOB_START = 'CREATE_JOB_START';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';

export const FETCH_NEXTJOBS_START = 'FETCH_NEXTJOBS_START';
export const FETCH_NEXTJOBS_SUCCESS = 'FETCH_NEXTJOBS_SUCCESS';
export const FETCH_NEXTJOBS_FAIL = 'FETCH_NEXTJOBS_FAIL';

export const FETCH_HISTORYJOBS_START = 'FETCH_HISTORYJOBS_START';
export const FETCH_HISTORYJOBS_SUCCESS = 'FETCH_HISTORYJOBS_SUCCESS';
export const FETCH_HISTORYJOBS_FAIL = 'FETCH_HISTORYJOBS_FAIL';

export const FETCH_JOB_START = 'FETCH_JOB_START';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

// Current User
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

