// Register for clients
export const REGISTER_CLIENT_START = 'REGISTER_CLIENT_START';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAIL = 'REGISTER_CLIENT_FAIL';

// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Login with Facebook
export const CLIENT_FACEBOOK_LOGIN_START = 'CLIENT_FACEBOOK_LOGIN_START';
export const CLIENT_FACEBOOK_LOGIN_SUCCESS = 'CLIENT_FACEBOOK_LOGIN_SUCCESS';
export const CLIENT_FACEBOOK_LOGIN_FAIL = 'CLIENT_FACEBOOK_LOGIN_FAIL';

// Properties
export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAIL = 'FETCH_PROPERTIES_FAIL';

// SHOW Property
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';

// Create Property
export const CREATE_PROPERTY_START = 'CREATE_PROPERTY_START';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAIL = 'CREATE_PROPERTY_FAIL';
